server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  service-url:
    default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: hostname
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: lb://user-service/
          predicates:
            - Path=/user/**
        - id: bike-service
          uri: lb://bike-service/
          predicates:
            - Path=/bike/**
        - id: car-svc
          uri: lb://car-svc/
          predicates:
            - Path=/car/**