server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway-service
          uri: https://github.com/ilgzmz/microservices-tutorial
          search-paths: config-data
  application:
    name: config-service